name: Generate ASCII Artwork

on: push

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >>dragon.txt
        
        - name: Sleep for 30sec
          run: sleep 30
    
    test_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10sec
          run: sleep 10
          
        - name: Test the cowsay file exists
          run: grep -i "dragon" dragon.txt
          
    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying..........